Repository shoppingflux/php-sdk, pull requests merged in 2018-06, with the labels that each got.

#35 #13 - order status update
  README.md
  composer.json
  docs/order.md
  phpunit.xml
  src/Api/Order/OrderCollection.php
  src/Api/Order/OrderDomain.php
  src/Api/Order/OrderOperation.php
  src/Api/Order/OrderResource.php
  src/Api/Order/OrderTicketCollection.php
  src/Api/Store/StoreResource.php
  src/Api/Task/TicketCollection.php
  src/Api/Task/TicketResource.php
  src/Operation/AbstractBulkOperation.php
  src/Order/Exception/TicketNotFoundException.php
  src/Order/Exception/UnexpectedTypeException.php
  src/Resource/AbstractResource.php
  tests/unit/Api/Order/OrderDomainTest.php
  tests/unit/Api/Order/OrderOperationTest.php
  tests/unit/Api/Order/OrderResourceTest.php
  tests/unit/Api/Order/OrderTicketCollectionMock.php
  tests/unit/Api/Order/OrderTicketCollectionTest.php
  tests/unit/Api/Store/StoreResourceTest.php
  tests/unit/Api/Task/TicketResourceTest.php
  tests/unit/Operation/AbstractBulkOperationTest.php
  tests/unit/Operation/BulkOperationMock.php
  tests/unit/Resource/AbstractDomainResourceTest.php
  tests/unit/Resource/AbstractResourceTest.php
  tests/unit/Resource/ResourceMock.php
Labels: enhancement

#39 #18 Order filter status
  CONTRIBUTING.md
  README.md
  docs/development/coding-standards.md
  docs/development/development.md
  docs/manual/authenticate.md
  docs/manual/error-handling.md
  docs/manual/resources/inventory.md
  docs/manual/resources/order.md
  src/Api/Order/OrderDomain.php
  src/Resource/AbstractDomainResource.php
  src/Resource/PaginationCriteria.php
  tests/unit/Api/Catalog/InventoryDomainTest.php
  tests/unit/Resource/AbstractDomainResourceTest.php
  tests/unit/Resource/PaginationCriteriaTest.php
Labels: enhancement

#42 Removing unnecessary generalisation that break inventory update
  src/Operation/AbstractBulkOperation.php
  tests/unit/Operation/AbstractBulkOperationTest.php
Labels: bug

#43 Doc - adding changelog file for release 0.2.0-beta.1
  CHANGELOG.md
Labels: docs

#46 Adding PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: architecture

#45 Add getter for session tokens
  src/Api/Session/SessionResource.php
  tests/unit/Api/Session/SessionResourceTest.php
Labels: enhancement

#48 Doc - changelog for v0.2.1-beta.1
  CHANGELOG.md
Labels: docs

#49 Changelog release v0.2.1-beta.1
  CHANGELOG.md
Labels: docs
