Repository shoppingflux/php-sdk, pull requests merged in 2018-10, with the labels that each got.

#62 Fix client version and add user agent platform info
  composer.json
  docs/manual/authenticate.md
  docs/manual/resources/inventory.md
  src/Client/Client.php
  src/Client/ClientOptions.php
  tests/unit/Client/ClientOptionsTest.php
Labels: bug, enhancement

#63 Add more info on session resource & getOne domain method
  src/Api/Catalog/InventoryDomain.php
  src/Api/Order/OrderDomain.php
  src/Api/Session/SessionResource.php
  src/Api/Store/StoreChannelDomain.php
  src/Api/Store/StoreChannelResource.php
  src/Api/Store/StoreResource.php
  src/Hal/HalLink.php
  src/Resource/AbstractDomainResource.php
  tests/unit/Api/AbstractResourceTest.php
  tests/unit/Api/Session/SessionResourceTest.php
  tests/unit/Api/Store/StoreResourceTest.php
  tests/unit/Hal/HalLinkTest.php
  tests/unit/Resource/AbstractDomainResourceTest.php
Labels: enhancement

#65 Small readme corrections
  CHANGELOG.md
  README.md
  docs/development/development.md
  docs/development/http-adapter.md
  docs/manual/authenticate.md
  docs/manual/error-handling.md
  docs/manual/resources/inventory.md
  docs/manual/resources/order.md
Labels: docs
