Repository shoppingflux/php-sdk, pull requests merged in 2018-04, with the labels that each got.

#6 #3 Add read objects for inventory domain
  doc/catalog.md
  doc/inventory.md
  readme.md
  src/Catalog/InventoryDomain.php
  src/Client/Client.php
  src/Guzzle/Middleware/RateLimitHandler.php
  src/Resource/AbstractDomainResource.php
  src/Resource/AbstractPaginatedCollection.php
  src/Resource/AbstractResource.php
  src/Resource/PaginatedResourceCollection.php
  src/Store/StoreResource.php
Labels: docs, enhancement

#5 Updating doc and adding docker config
  CONTRIBUTING.md
  Dockerfile
  README.md
  composer.json
  docker-compose.yml
  docs/authenticate.md
  docs/catalog.md
  docs/development.md
  docs/error-handling.md
Labels: composer-install, docs

#23 Add Gzip as accepted encoding
  src/Hal/HalClient.php
Labels: enhancement
