Repository shoppingflux/php-sdk, pull requests merged in 2020-04, with the labels that each got.

#87 Add property itemsReferencesAliases
  src/Api/Order/OrderResource.php
  tests/unit/Api/Order/OrderResourceTest.php
Labels: enhancement

#89 Adding changelog for 0.3.0 and 0.3.1
  CHANGELOG.md
Labels: docs

#90 Fix typo in docs/development/http-adapter.md
  docs/development/http-adapter.md
Labels: docs

#91 Do not decode empty response
  src/Hal/HalClient.php
  tests/unit/Hal/HalClientTest.php
Labels: bug
